var GAME_LEVELS = [
["xxxxxxxxxxxxxxxxxxxx",
   "x@x    x x x    x dx",
   "x x   2x   x    xxvx",
   "x x  xr> c x x   x x",
   "x    x   x   x   x x",
   "xc  xxf  x  fxx   cx",
   "x    xx  x  xx     x",
   "x    xc  x  cx   x x",
   "x x  x x c <lx   x x",
   "x x^   x   x    xx x",
   "x xu c x x x c  x  e",
   "xxxxxxxxxxxxxxxxxxxx"],
   ["xxxxxxxxxxxxxxxxxxxx",
    "x@  dxc      c  p  x",
    "xc  vx     <lx    cx",
    "xxxx xxx x   x  xxxx",
    "x    x   x   x     x",
    "x c  x  cxc  x^    x",
    "x    x xxxxx xu c  x",
    "x xxxx  cxc  xxxx  x",
    "xc d x   x  cx     x",
    "x  v x   x xxx c   x",
    "x    x       x    cx",
    "x  c x       x xxxxx",
    "x            xr>  ce",
    "x  c h     <lx     x",
    "xxxxxxxxxxxxxxxxxxxx"],
    ["xxxxxxxxxxxxxxxxxxxx",
     "xxc    x  d  x   cxx",
     "xcxc   x  v  x  cxcx",
     "x cxc          cxc x",
     "x  cx    x2x   xc  x",
     "x       x   x      x",
     "x         x        x",
     "xr>p  x   @   x f<le",
     "x         x        x",
     "x       x   x      x",
     "x  cx    xfx   xc  x",
     "x cxc          cxc x",
     "xcxc   x  ^  x  cxcx",
     "xxc    x  u  x   cxx",
     "xxxxxxxxxxxxxxxxxxxx"]
    ];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;