var GAME_LEVELS = [
  ["xxxxxxxxxxxxxxxxxxxx",
   "x@x    x x x    x  x",
   "x x    x   x    xx x",
   "x x  x   c x x   x x",
   "x    x   x   x   x x",
   "xc  xxf  x  fxx   cx",
   "x    xx  x  xx     x",
   "x    xc  x  cx   x x",
   "x x  x x c   x   x x",
   "x x    x   x    xx x",
   "x x  c x x x c  x  e",
   "xxxxxxxxxxxxxxxxxxxx"],
  ["xxxxxxxxxxxxxxxxxxxx",
   "x@x    x x x    x  x",
   "x x    x   x    xx x",
   "x x  x   c x x   x x",
   "x    x   x   x   x x",
   "xc  xxf  x  fxx   cx",
   "x    xx  x  xx     x",
   "x    xc  x  cx   x x",
   "x x  x x c   x   x x",
   "x x    x   x    xx x",
   "x x  c x x x c  x  e",
   "xxxxxxxxxxxxxxxxxxxx"],
   ["xxxxxxxxxxxxxxxxxxxx",
   "x@x    x x x    x  x",
   "x x    x   x    xx x",
   "x x  x   c x x   x x",
   "x    x   x   x   x x",
   "xc  xxf  x  fxx   cx",
   "x    xx  x  xx     x",
   "x    xc  x  cx   x x",
   "x x  x x c   x   x x",
   "x x    x   x    xx x",
   "x x  c x x x c  x  e",
   "xxxxxxxxxxxxxxxxxxxx"],
   ["xxxxxxxxxxxxxxxxxxxx",
   "x@x    x x x    x  x",
   "x x    x   x    xx x",
   "x x  x   c x x   x x",
   "x    x   x   x   x x",
   "xc  xxf  x  fxx   cx",
   "x    xx  x  xx     x",
   "x    xc  x  cx   x x",
   "x x  x x c   x   x x",
   "x x    x   x    xx x",
   "x x  c x x x c  x  e",
   "xxxxxxxxxxxxxxxxxxxx"]];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;